destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/qumulo-doc"
port: 4010
output: pdf
product: Qumulo on Azure as a Service Getting Started Guide
print_title: Qumulo on Azure as a Service Getting Started Guide
#print_subtitle: version 6.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: azure_sidebar
